import { useState, useRef, useEffect } from 'react';

export default function PlaylistView({
  playlist,
  files,
  apiBase,
  authToken,
  onAddFile,
  onRemoveFile,
  onMoveFile,
  onReorder,
  formatBytes,
  formatDate,
}) {
  const [dragOver, setDragOver] = useState(false);
  const [dragFile, setDragFile] = useState(null);
  const [dragIndex, setDragIndex] = useState(null);
  const [dragType, setDragType] = useState(null);
  const [dragOverIndex, setDragOverIndex] = useState(null);
  const [dragOverType, setDragOverType] = useState(null);
  const [dragOverPlaylist, setDragOverPlaylist] = useState(null);
  const [dragOverPlaylistIndex, setDragOverPlaylistIndex] = useState(null);
  const [dragOverPlaylistType, setDragOverPlaylistType] = useState(null);
  const [dragOverPlaylistFiles, setDragOverPlaylistFiles] = useState([]);
  const [dragOverPlaylistFilesIndex, setDragOverPlaylistFilesIndex] = useState(null);
  const [dragOverPlaylistFilesType, setDragOverPlaylistFilesType] = useState(null);
  const [dragOverPlaylistFilesFiles, setDragOverPlaylistFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesIndex, setDragOverPlaylistFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesType, setDragOverPlaylistFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFiles, setDragOverPlaylistFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles] = useState([]);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesIndex] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType, setDragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesType] = useState(null);
  const [dragOverPlaylistFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFilesFiles